### ISSUE TITLE
CompileShaders concurrency issue on 32-core Threadripper

### ISSUE THREAD

**Issue by BattleAxeVR** [NVIDIA-RTX/NRD#1]
Hi there, I had some issues compiling the shaders, both using the batch file and in SANDBOX.sln. I tried inspecting why some of the shader compiles were timing out by checking their command line strings and running each manually in CMD, and they compiled just fine. Also, the hang was occurring on different shaders debug and release, so I figured it was a timing or a race condition.

In CompileShaders.cpp, I simply forced the number of hardware threads to 1 from my default of 64 (AMD TR4 2990wx CPU, 32 cores with 64 threads), and voila, no hangs and it compiles them all successfully without hanging or timeouts.

const size_t threadNum = 1; // std::thread::hardware_concurrency();

I suspect there's something going on inside dxc.exe when operating on the same included files concurrently. Maybe it's just on my CPU, I guess not everyone has 32-core CPUs :)

**Comment by BattleAxeVR** [comment]
I suspect the bug is in this line, come to think of it.

 const size_t shadersPerThread = std::max<size_t>((shaders.size() + (threadNum - 1)) / threadNum, 1);

forcing threadnum to 1 makes shaderPerThread just the number of shaders, whereas with threadNum as 64, it hangs. I think it's just stomping memory or trying to compile the same shader twice concurrently, maybe.

**Comment by dzhdanNV** [comment]
Thanks. The problem is clear. We will fix.

**Comment by dzhdanNV** [comment]
@BattleAxeVR Fixed. Please, verify.

**Comment by BattleAxeVR** [comment]
Works perfectly now, thanks.
