### ISSUE TITLE
VS 2019 build problem

### ISSUE THREAD

**Issue by BattleAxeVR** [NVIDIA-RTX/NRD#10]
Hi, thanks for the help fixing the build for vs2017 today, but there's a compile error relating to vector intrinsics when I call 1-Deploy.bat vs2019, or open it up manually and build in 2019.

Also 2-Build.bat is hardcoded to point to the vs2017 solution path instead of %1, but that's minor and doesn't matter as much (just wanted to let you know, for completeness).

**Comment by dzhdanNV** [comment]
Fixed. Please, update, check & close if it works.

**Comment by BattleAxeVR** [comment]
Yes indeed, it works perfectly now. Thanks.

One small touch that would be a nice to have is if you could add a .gitignore containing the build folders:

_Build/
_Compiler/
_Data/
_NRD/

**Comment by dzhdanNV** [comment]
There is "0-Clean.bat" for this purpose. These folders are automatically generated and don't contain anything, what needs to be kept in the repository. In other words, if you want to commit something:
- call "0-Clean.bat" first
- commit your changes

**Comment by dzhdanNV** [comment]
@BattleAxeVR you have convinced me (sorry I'm a GitHub noob) - I have added .gitignore
