### ISSUE TITLE
Depth of field, can it be denoised with NRD?

### ISSUE THREAD

**Issue by BattleAxeVR** [NVIDIA-RTX/NRD#19]
Hi, I've been tinkering with Nvidia's vk_raytrace sample and noticed it now supports non-zero aperture and a variable focal distance for Depth of Field. 

It looks great so it would be fantastic if it could be done in realtime with NRD / Reblur. 

Before I spent any time trying to modify NRD to support it, can you tell me if this is likely to succeed?

**Comment by dzhdanNV** [comment]
Nope. REBLUR / RELAX perform geometry tracking with explicit properties - position, normal + material props. It's not applicable to DOF, something else is needed here. Theoretically, a new type of denoiser can appear one day :) but if you start using REBLUR / RELAX as is, you will see how DOF signal starts to follow surfaces - it's wrong and will look strange.
