### ISSUE TITLE
Blue output in Vulkan mode (NRD Bistro scene)

### ISSUE THREAD

**Issue by BattleAxeVR** [NVIDIA-RTX/NRD#2]
Hello again, ran into another issue. It looks like the blue and red channels are swapped in Vulkan mode

![image](https://user-images.githubusercontent.com/11604039/97961831-fb5b8d80-1d81-11eb-838d-11b21f5c4077.png)

Here's the repro command line: 

_Build\vs2017\Bin\Release\09_RayTracing_NRD.exe --api=VULKAN --width=1280 --height=720 --testMode --scene=Bistro/BistroInterior.fbx

I just updated my drivers to 457.09 regular, I was on beta drivers (for KHR ray tracing support) 457.00 before, which was also blue but had some glitchy stuff at the top. 

I'm using Visual Studio 2019, latest Windows 10 SDK, and Vulkan SDK 1.2.154.1. I also tried two different versions of the dxc.exe, the one that's included in Windows 10 kits, and another version that's needed for Vulkan 1.2 support. Both give me blue, but otherwise work fine.

I just checked the 3a--.bat test suite, and Vulkan looks identical to DX12 in all the tests, except the NRD one. The shaderballs uses an obj file format (instead of FBX) and it also has swapped R<->B colour channels, so we know the issue isn't in the loader but the NRD code. I'll look around to see if it's something obvious (probably is).

Great job by the way, the bistro scene is stunning. What amazing tech.

**Comment by dzhdanNV** [comment]
Thanks. Fixed. Updated will be uploaded soon.

**Comment by dzhdanNV** [comment]
@BattleAxeVR Fixed. Please, verify.

**Comment by BattleAxeVR** [comment]
Yep, fixed too. 

The latest beta driver (for KHR Vulkan RT extensions) still has some weird square artifacts on my RTX 2080 Ti, but that's something else.
