### ISSUE TITLE
NRI SDK deployment does not copy DLL

### ISSUE THREAD

**Issue by pixnblox** [NVIDIA-RTX/NRD#22]
The NRI SDK deployment batch script does not copy the debug / release NRI DLL (NRI.dll):

`4a-Prepare NRI SDK.bat`
https://github.com/NVIDIAGameWorks/RayTracingDenoiser/blob/93ea3f5e1c1c330aa0ce4a477b74d96516e47513/4a-Prepare%20NRI%20SDK.bat

This DLL is necessary to run the sample application, and so presumably should be part of a complete SDK. The NRD deployment script does copy the NRD DLL.

**Comment by dzhdanNV** [comment]
Thanks. It will be fixed in the upcoming update.

**Comment by dzhdanNV** [comment]
Fixed.
