### ISSUE TITLE
ReLAX Prepass and/or Reproject turns zeroed radiance values into nan

### ISSUE THREAD

**Issue by LeonBrands** [NVIDIA-RTX/NRD#27]
**Prepass:**
Before:
![image](https://user-images.githubusercontent.com/15885946/141765211-5b653be0-abb3-4576-8bfb-6497f10d6f0d.png)

After:
![image](https://user-images.githubusercontent.com/15885946/141765272-c158399a-5f01-4eb4-b74f-863a01559609.png)

If prepass is disabled entirely, reproject will cause similar issues
**Reproject:**
Before:
![img](https://user-images.githubusercontent.com/15885946/141767637-ae0a53aa-73ca-4ef8-8921-6303570c578d.png)
After:
![img](https://user-images.githubusercontent.com/15885946/141767682-0029ba7f-cb6e-43a3-a27b-721207364eed.png)

**Comment by ttcheblokov** [comment]
What is the linearZ value for those NaN pixels in ReLAX?

**Comment by LeonBrands** [comment]
They're defaulted to 0

**Comment by ttcheblokov** [comment]
Can you initialize linear Z to nonzero value, ideally > CommonSettings::denoisingRange ?

**Comment by LeonBrands** [comment]
That seems to fix it!
