### ISSUE TITLE
Initial window position

### ISSUE THREAD

**Issue by Firnor** [NVIDIA-RTX/NRD#3]
I'am currently having some issues with the window that is positioned weirdly (see screen shot below, for privacy reasons I covered the unimportant regions with red, I also highlighted the border between the screens with a red line).
![issue](https://user-images.githubusercontent.com/1177733/98349445-47286400-201a-11eb-8741-bd2c667807a4.png)

In particular, when starting the application (via 3b-RunNRDSample.bat or manually) the window is opened in the center between my 2 screens (dual monitor setup). So one half of the window is on one screen and the other half on the other one.
It also seems to automatically enable borderless fullscreen if the resolution is set to the native resolution of the screen, which is generally fine except in my case I cannot move the window anymore and it is stuck inbetween my 2 screens.

Using a resolution below the native resolution leads to a window with border and title bar which can be moved withut any issues.

**Comment by dzhdanNV** [comment]
Yes, the framework doesn't handle multi-monitor setup. It sets the position to the center of the virtual desktop. You can change this behavior in:

SampleBase.cpp: 680
bool SampleBase::Create(...)

There is a comment saying that multi-monitor is not supported.

**Comment by Firnor** [comment]
Is there any downside to changing this to **SM_CXSCREEN** and **SM_CXSCREEN** respectively?
This would use the resolution of the primary monitor and fixes this issue for multi-monitor setups while not changing a thing for single-monitor setups.

**Comment by dzhdanNV** [comment]
Yes, in 77% of cases :) But what if want to get a huge window covering the entire virtual desktop. I will think about it. Don't want to over-compilate.

**Comment by Firnor** [comment]
I see.
Then maybe a simple command line option like _--fullvirtualscreen_ for that situation would do the job

**Comment by dzhdanNV** [comment]
Fixed. Changed to SM_CXSCREEN and SM_CXSCREEN. Please, update and check.

**Comment by Firnor** [comment]
Works now, thanks.
