### ISSUE TITLE
Artifacts on Vulkan with beta drivers

### ISSUE THREAD

**Issue by Firnor** [NVIDIA-RTX/NRD#4]
When using the vulkan backend, I get huge artifacts in the top region of the image as well as random flickering (horizontal lines, multiple pixels in height). This may be related to the glitches mentioned in #2. 
![issue2](https://user-images.githubusercontent.com/1177733/98350283-6a074800-201b-11eb-9fa4-48cc4010023a.png)

I'm using:
- Visual Studio 2019
- latest Windows SDK
- Vulkan SDK 1.2.141.2
- Nvidia RTX 2070 Super (beta drivers: 457.00)

I need the beta drivers for support of VK_KHR_ray_tracing in a different project. 
Furthermore, when debugging the application with Nvidia Nsight Graphics, everything seems fine after ray tracing, so the issue should lie elsewhere. 
From a quick glance, I noticed that the artifacts first appear in the "Translucent shadow - pre blur" pass, specifically in the "gln_History" image.

**Comment by dzhdanNV** [comment]
I fixed many VK related issues in the sample. The update is coming (today). But I have never seen corruptions in VK mode on release drivers. Please, try the latest public (release) driver.

**Comment by dzhdanNV** [comment]
> From a quick glance, I noticed that the artifacts first appear in the "Translucent shadow - pre blur" pass, specifically in the "gln_History" image.

Thanks. It can be a hint. But let's start with trying the latest version on the latest public drivers.

**Comment by Firnor** [comment]
Thanks a lot.
However, as I mentioned:
> I need the beta drivers for support of VK_KHR_ray_tracing in a different project.

Sadly, this makes it currently impossible to combine the denoiser with a custom ray tracing implementation using the VK_KHR_ray_tracing extension as long as it's not fully specified and implemented in regular drivers.
I understand that you will not support this until it's in a release version, I just want to point it out if others face the same issues.

**Comment by dzhdanNV** [comment]
The latest will appear on GitHub in 30 mins. Please, try it and let me know. You are not alone in facing this issue. It can be:
- an NRD sample VK API usage issue or
- a beta driver problem
I will try to help to resolve it

**Comment by dzhdanNV** [comment]
@Firnor I updated the repo to NRD v1.8.10. Please, check it. Just in case - NRD is API agnostic, it doesn't contain any GAPI related code. The problem, we are discussing, can be NRD sample related, but not NRD.

**Comment by Firnor** [comment]
Unfortunately, there are still the same corruption artifacts.

>NRD is API agnostic, it doesn't contain any GAPI related code. The problem, we are discussing, can be NRD sample related, but not NRD.

Thanks for pointing that out. Then there should be no conflicts of NRD and beta drivers.
So I think the easiest solution would be to setup a machine with release drivers for toying around with NRD in a sandbox environment. Don't want to bother you with fixing stuff for beta drivers :)

Unrelated to that: In addition, now the application crashes when moving the window to a different screen (probably on swap chain recreation). I can investigate this problem further and create a new issue here.

**Comment by Firnor** [comment]
Edit to the last paragraph:
The application stops (debug break) because the swap chain is out of date and there is no swap chain recreation mechanism.
The issue appears after moving the window due to wrong positioning on a multi-monitor setup (see #3).

**Comment by dzhdanNV** [comment]
Thanks, it's possible. NRI FRAMEWORK is not an engine. I will ask what we (NRI devs) want to have in the framework. But, unfortunately, the last request looks like "will never implement". Please, close this one - if you are ready. And open a new one as a first stone in The Hall of Blame :)

**Comment by Firnor** [comment]
Alright, thanks!
