### ISSUE TITLE
No swap chain recreation in Vulkan backend

### ISSUE THREAD

**Issue by Firnor** [NVIDIA-RTX/NRD#5]
When the window is resized, for example by moving it between two screens with different resolution, the application stops without a proper error message.
This problem is caused by directly exiting when present returns that the swap chain is out of date.
Fixing this issue would require the swap chain to be recreated when out of date.

**Comment by dzhdanNV** [comment]
I don't think that it is a requirement for a sample application. It won't be fixed.
