### ISSUE TITLE
NSight graphics on Vulkan: "Acceleration structure tracking failed an integrity check"

### ISSUE THREAD

**Issue by BattleAxeVR** [NVIDIA-RTX/NRD#6]
![image](https://user-images.githubusercontent.com/11604039/99351777-5a83cc80-286f-11eb-9a49-a8d8c0516d46.png)

Not sure if this is a serious issue, but thought I'd report it just the same. Also the bistro scene.

Using latest Nsight graphics version (2020.5.2), Vulkan SDK 1.2.154.1, and beta Nvidia drivers v457.33 on an RTX 2080 Ti.

**Comment by BattleAxeVR** [comment]
The link it points to is here:

https://docs.nvidia.com/nsight-graphics/UserGuide/index.html#troubleshooting_problem___acceleration_structure_integrity_check_failed

Something about the geometry buffers being updated. Maybe it explains the already-reported visual glitches seen in the beta drivers?

**Comment by dzhdanNV** [comment]
A note - this paragraph says that it can be an NSIGHT related problem... Despite that it can be a bug, please, do not make conclusions without 100% data
